FROM alpine:3.13

LABEL Maintainer="Loi Tra <loi.tra@9thwonder.com>"
LABEL Description="Lightweight webstack with latest Nginx & PHP 7.0 & s6-overlay based on Alpine Linux."

RUN apk -U upgrade && apk add --no-cache \
    bash \
    curl \
    nginx \
    php8 \
    php8-ctype \
    php8-curl \
    php8-dom \
    php8-fpm \
    php8-gd \
    php8-intl \
    php8-json \
    php8-mbstring \
    php8-mysqli \
    php8-opcache \
    php8-openssl \
    php8-phar \
    php8-session \
    php8-xml \
    php8-xmlreader \
    php8-zlib \
    tzdata \
    && ln -s /usr/sbin/php-fpm8 /usr/sbin/php-fpm \
    && addgroup -S php \
    && adduser -S -G php php \
    && rm -rf /var/cache/apk/* /etc/nginx/conf.d/*
#/etc/php8/conf.d/* /etc/php8/php-fpm.d/*

RUN ln -s /usr/bin/php8 /usr/bin/php

COPY files/s6-overlay files/general files/php8 /

WORKDIR /www

RUN chmod o+x /opt/utils/docker_entrypoint.sh; chmod 755 /opt/utils/docker_entrypoint.sh;
ENTRYPOINT ["bash", "/opt/utils/docker_entrypoint.sh"]
CMD ["/init"]

EXPOSE 80

HEALTHCHECK --interval=5s --timeout=5s CMD curl -f http://127.0.0.1/php-fpm-ping || exit 1
