FROM alpine:3.13
#FROM alpine

LABEL Maintainer="Loi Tra <loi.tra@9thwonder.com>"
LABEL Description="Lightweight webstack with latest Apache & PHP 7.0 & s6-overlay based on Alpine Linux."

RUN apk -U upgrade && apk add --no-cache \
    bash \
    curl \
    apache2 \
    php7-apache2 \
    && mkdir -p /opt/utils \
    && ln -s /usr/sbin/php-fpm7 /usr/sbin/php-fpm \
    && addgroup -S php \
    && adduser -S -G php php \
    && rm -rf /var/cache/apk/*
#/etc/php7/conf.d/* /etc/php7/php-fpm.d/*

COPY files/s6-overlay files/general files/php7 /

# Enable options supported by this version of PHP-FPM
RUN sed '/decorate_workers_output/s/^; //g' /etc/php7/php-fpm.conf

RUN set -eux; \
    # Change apache config \
    #sed -i 's/#ServerAdmin\ you@example.com/ServerAdmin\ you@example.com/' /etc/apache2/httpd.conf \
    #sed -i 's/#ServerName\ www.example.com:80/ServerName\ www.example.com:80/' /etc/apache2/httpd.conf \
    sed -i 's#^DocumentRoot ".*#DocumentRoot "/var/www/html"#g' /etc/apache2/httpd.conf; \
    sed -i 's#Directory "/var/www/localhost/htdocs"#Directory "/var/www/html"#g' /etc/apache2/httpd.conf; \
    sed -i 's#AllowOverride None#AllowOverride All#' /etc/apache2/httpd.conf; \
    # Enable commonly used apache modules \
    sed -i 's/#LoadModule\ rewrite_module/LoadModule\ rewrite_module/' /etc/apache2/httpd.conf; \
    sed -i 's/#LoadModule\ deflate_module/LoadModule\ deflate_module/' /etc/apache2/httpd.conf; \
    sed -i 's/#LoadModule\ expires_module/LoadModule\ expires_module/' /etc/apache2/httpd.conf; \
    # Modify php.ini settings \
    sed -i 's/memory_limit = .*/memory_limit = 256M/' /etc/php7/php.ini; \
    sed -i "s/^;date.timezone =$/date.timezone = \"Europe\/Stockholm\"/" /etc/php7/php.ini;

# Logging
# RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log && \
#     ln -sf /proc/self/fd/1 /var/log/apache2/error.log

EXPOSE 80

WORKDIR /var/www/html

CMD ["/init"]

# HEALTHCHECK --interval=5s --timeout=5s CMD curl -f http://127.0.0.1/php-fpm-ping || exit 1
HEALTHCHECK --interval=5s --timeout=5s CMD wget -q --no-cache --spider localhost || exit 1
