FROM alpine:3.13

LABEL Maintainer="Loi Tra <loi.tra@9thwonder.com>"
LABEL Description="Lightweight webstack with latest Nginx & PHP 7.0 & s6-overlay based on Alpine Linux."

RUN apk -U upgrade && apk add --no-cache \
    bash \
    curl \
    nginx \
    php8 \
    php8-fpm \
    tzdata \
    && ln -s /usr/sbin/php-fpm8 /usr/sbin/php-fpm \
    && addgroup -S php \
    && adduser -S -G php php \
    && rm -rf /var/cache/apk/* /etc/nginx/conf.d/*
#/etc/php8/conf.d/* /etc/php8/php-fpm.d/*

# Create symlink so programs depending on `php` still function
RUN ln -s /usr/bin/php8 /usr/bin/php

COPY files/s6-overlay files/general files/php8 /

RUN set -eux; \
    sed -i 's/memory_limit = .*/memory_limit = 256M/' /etc/php7/php.ini; \
    sed -i 's/max_execution_time = .*/max_execution_time = 60/' /etc/php7/php.ini; 

WORKDIR /var/www/html

CMD ["/init"]

EXPOSE 80

HEALTHCHECK --interval=5s --timeout=5s CMD curl -f http://127.0.0.1/php-fpm-ping || exit 1
