name: Build containers

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tag: ["7.4", "8.0"]
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v2
      - name: Build the container
        run: make build TAG=$(printenv TAG)
        env:
          TAG: ${{ matrix.tag }}
      - name: Start the container
        run: make start TAG=$(printenv TAG) && sleep 10
        env:
          TAG: ${{ matrix.tag }}
      - name: Test the container
        run: make test TAG=$(printenv TAG)
        env:
          TAG: ${{ matrix.tag }}
      # - name: Login to Docker Hub
      #   if: github.repository_owner == '9thWonder-VNTeam' && github.ref == 'refs/heads/master'
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the container to Docker Hub # TODO: to be changed to AWS ECR
        env:
          TAG: ${{ matrix.tag }}
        if: github.repository_owner == '9thWonder-VNTeam' && github.ref == 'refs/heads/master'
        run: docker push 298862221448.dkr.ecr.us-east-1.amazonaws.com/nginx-php:$(printenv TAG)
